
'use client';

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { useRouter, usePathname } from 'next/navigation';
import { useIdleTimer } from '@/hooks/use-idle-timer';
import { toast } from '@/hooks/use-toast';

type Language = 'RU' | 'EN';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  RU: {
    // Landing / SEO
    'landing.headline': 'Найди свою идеальную пару сегодня',
    'landing.subheadline': 'SwiftMatch — умный способ познакомиться с интересными людьми рядом.',
    'landing.stats.users.num': '1M+',
    'landing.stats.users.label': 'Пользователей',
    'landing.stats.matches.num': '500K',
    'landing.stats.matches.label': 'Совпадений',
    'landing.stats.countries.num': '50+',
    'landing.stats.countries.label': 'Стран',
    
    // Bottom Nav
    'nav.home': 'Главная',
    'nav.search': 'Поиск',
    'nav.activity': 'Активность',
    'nav.chats': 'Чаты',
    'nav.profile': 'Профиль',
    // Common Buttons
    'button.continue': 'Продолжить',
    'button.skip': 'Пропустить',
    'button.save': 'Сохранить',
    'button.back': 'Назад',
    'button.like': 'Лайк',
    'button.message': 'Сообщение',
    'button.send': 'Отправить',
    'button.search': 'Поиск',
    'button.filters': 'Фильтры',
    'button.autosearch': 'Автопоиск',
    'button.load_more': 'Показать еще',
    'button.start': 'Начать знакомства',
    'button.write_first': 'Написать первым',
    'button.close': 'Закрыть',
    'button.unlock': 'Разблокировать бесплатно',
    'button.watch': 'Смотреть',
    'button.not_now': 'Не сейчас',
    'button.report': 'Пожаловаться',
    'button.browse_profiles': 'Люди рядом',
    // Profile
    'profile.edit': 'Изменить',
    'profile.about': 'О себе',
    'profile.lifestyle': 'Данные',
    'profile.interests': 'Интересы',
    'profile.gallery': 'Галерея',
    'profile.add': 'Добавить',
    'profile.likes': 'Лайков',
    'profile.matches': 'Мэтчей',
    'profile.age': 'Возраст',
    'profile.city': 'Москва',
    'profile.goal': 'Цель',
    'profile.goal_value': 'Серьезные отношения',
    'profile.height': 'Рост',
    'profile.pro': 'PRO 💎',
    'profile.someone': 'Кто-то',
    // Lifestyle Labels
    'profile.label.zodiac': 'Зодиак',
    'profile.label.height': 'Рост',
    'profile.label.goal': 'Цель',
    'profile.label.education': 'Образование',
    'profile.label.job': 'Работа',
    'profile.label.pets': 'Питомцы',
    'profile.label.sleep': 'Режим сна',
    'profile.label.gender': 'Пол',
    'profile.label.looking_for': 'Ищу',
    // Activity
    'activity.title': 'События',
    'activity.likes': 'Лайки',
    'activity.visits': 'Визиты',
    'activity.all': 'Все',
    'activity.new': 'новых',
    'activity.empty': 'Ничего не найдено',
    'activity.today_activity': 'Ваша активность сегодня',
    'activity.msg_like': 'поставила вам лайк',
    'activity.msg_visit': 'посетила ваш профиль',
    'activity.msg_match': 'новое совпадение с вами!',
    'activity.unlock_title': 'Бонус',
    'activity.unlock_desc': 'Посмотрите рекламу, чтобы открыть анкету бесплатно на 24 часа.',
    'activity.premium_title': 'Premium Доступ',
    'activity.premium_desc': 'Узнайте, кому вы понравились, и получите безлимитные лайки!',
    // Boost
    'boost.title': 'Поднять анкету',
    'boost.desc': 'Ваш профиль увидят в 10 раз больше людей в течение часа!',
    'boost.free': 'Бесплатно за рекламу',
    'boost.paid': 'Купить мгновенно',
    'boost.success_ad': 'Буст активирован за просмотр рекламы! 🔥',
    'boost.success_paid': 'Буст успешно куплен и активирован! 🔥',
    'autosearch.title': 'Доступ к Автопоиску',
    'autosearch.desc': 'Получите доступ к умному поиску, посмотрев рекламу или оплатив.',
    'autosearch.free': 'Бесплатно за рекламу',
    'autosearch.paid': 'Купить доступ',
    'autosearch.success_ad': 'Доступ к Автопоиску открыт!',
    'autosearch.success_paid': 'Доступ к Автопоиску куплен!',
    // Chats
    'chats.title': 'Сообщения',
    'chats.subtitle': 'Твои диалоги',
    'chats.search': 'Поиск по чатам...',
    'chats.online': 'В сети',
    'chats.offline': 'Был(а) недавно',
    'chats.today': 'Сегодня',
    'chats.typing': 'печатает...',
    'chats.ai_themes': 'Темы ответов AI',
    'chats.close_themes': 'Закрыть темы',
    'chats.placeholder': 'Ваше сообщение...',
    // Home / Search
    'home.popular': 'Популярное сейчас',
    'home.headline': 'Твой идеальный мэтч ждет тебя',
    'home.subheadline': 'Знакомься, общайся и находи любовь',
    'home.top_week': 'Топ недели',
    'home.recommend': 'Рекомендуем',
    'home.nearby': 'Люди рядом',
    'home.searching': 'Ищем лучших для вас...',
    'home.results': 'Результаты',
    'home.no_results': 'По вашим параметрам пока никого нет.',
    'match.title': 'Это совпадение!',
    'match.desc': 'Вы понравились друг другу. Не заставляйте ждать!',
    'match.insight': 'AI Инсайт',
    'swipes.nearby': 'анкет рядом',
    'match.insight_default': 'Вы отлично подходите друг другу!',
    // Filter
    'filter.who_to_see': 'Кого вы ищете?',
    'filter.distance': 'Расстояние',
    'filter.goal': 'Цель знакомства',
    'filter.goal.all': 'Любая цель',
    'filter.gender.all': 'Все',
    'filter.gender.male': 'Мужчины',
    'filter.gender.female': 'Женщины',
    // Onboarding
    'onboarding.step1.title': 'Как тебя зовут?',
    'onboarding.step1.desc': 'Имя будет отображаться в твоем профиле.',
    'onboarding.step1.label': 'Имя',
    'onboarding.step1.placeholder': 'Твое имя',
    'onboarding.step1.gender_label': 'Твой пол',
    'onboarding.step1.male': 'Мужчина',
    'onboarding.step1.female': 'Женщина',
    'onboarding.step2.title': 'Немного деталей',
    'onboarding.step2.desc': 'Это поможет нам найти людей поблизости.',
    'onboarding.step2.age': 'Возраст',
    'onboarding.step2.height': 'Рост (см)',
    'onboarding.step2.city': 'Город (опционально)',
    'onboarding.step2.city_placeholder': 'Где ты находишься?',
    'onboarding.step3.title': 'Личное',
    'onboarding.step3.desc': 'Расскажи о своих целях и знаке зодиака.',
    'onboarding.step3.goal_label': 'Цель знакомства',
    'onboarding.step3.goal_placeholder': 'Выберите цель',
    'onboarding.step3.zodiac_label': 'Знак зодиака',
    'onboarding.step3.zodiac_placeholder': 'Выберите знак',
    'onboarding.step4.title': 'Твои интересы',
    'onboarding.step4.desc': 'Выбери минимум 1, чтобы AI составил крутое био.',
    'onboarding.step5.title': 'Почти готово!',
    'onboarding.step5.desc': 'Добавь яркое фото и расскажи о себе или позволь AI помочь.',
    'onboarding.step5.photo_label': 'Выбрать фото',
    'onboarding.step5.bio_label': 'О себе',
    'onboarding.step5.bio_placeholder': 'Расскажи о своих увлечениях...',
    'onboarding.toast.photo_added': 'Фото добавлено!',
    'onboarding.toast.photo_desc': 'Ваш профиль теперь выглядит отлично.',
    'onboarding.toast.bio_ai': 'Био создано AI',
    'onboarding.toast.finish_title': 'Профиль готов!',
    'onboarding.toast.finish_desc': 'Добро пожаловать в SwiftMatch.',
    'onboarding.loc.detecting': 'Определяем местоположение...',
    'onboarding.loc.success': 'Город определен: ',
    'onboarding.loc.fail': 'Не удалось определить город',
    'onboarding.loc.denied': 'Доступ к геолокации отклонен',
    // Report
    'report.title': 'Жалоба на пользователя',
    'report.description': 'Ваша жалоба анонимна. Выберите причину, и мы рассмотрим ситуацию.',
    'report.reason.spam': 'Спам',
    'report.reason.abuse': 'Оскорбительное поведение',
    'report.reason.fake': 'Фейковый профиль',
    'report.reason.scam': 'Мошенничество',
    'report.reason.content': 'Неприемлемый контент',
    'report.details_placeholder': 'Дополнительные детали (необязательно)',
    'report.button.send': 'Отправить жалобу',
    'report.button.cancel': 'Отмена',
    'report.toast.success_title': 'Жалоба отправлена',
    'report.toast.success_desc': 'Спасибо! Мы рассмотрим вашу жалобу на',
    'report.toast.no_reason_title': 'Выберите причину',
    'report.toast.no_reason_desc': 'Необходимо указать причину для отправки жалобы.',
    // Settings
    'settings.account': 'Аккаунт',
    'settings.push_notifications': 'Push-уведомления',
    'settings.email_newsletter': 'Email-рассылка',
    'settings.location': 'Геолокация',
    'settings.discovery': 'Показывать меня',
    'settings.privacy': 'Приватность',
    'settings.incognito': 'Инкогнито',
    'settings.security': 'Безопасность',
    'settings.security.status': 'OK',
    'settings.support': 'Поддержка',
    'settings.support.chat_title': 'Написать в поддержку',
    'settings.support.chat_desc': 'Чат с нашей командой',
    'logout.title': 'Вы вышли из системы',
    'logout.button': 'Выйти',
    'delete_profile.button': 'Удалить профиль',
    // Support Chat
    'support.title': 'Служба поддержки',
    'support.placeholder': 'Напишите ваше сообщение...',
    'support.greeting': 'Здравствуйте! Чем мы можем вам помочь?',
    'support.response': 'Спасибо за ваше сообщение! Наш специалист скоро с вами свяжется.',
    'support.faq_promo': 'Не нашли ответ? Посетите наш',
    'support.faq_promo_link': 'раздел FAQ',
    // FAQ
    'faq.title': 'Вопросы и ответы',
    'faq.page_title': 'Часто задаваемые вопросы',
    'faq.description': 'Ответы на популярные вопросы',
    'faq.q1.question': 'Как я могу изменить свое фото профиля?',
    'faq.q1.answer': 'Вы можете изменить свои фотографии, перейдя в свой профиль, нажав на кнопку "Изменить" и затем на вашу главную фотографию или на свободные слоты в галерее.',
    'faq.q2.question': 'Безопасны ли мои платежные данные?',
    'faq.q2.answer': 'Да, абсолютно. Мы используем ведущие в отрасли платежные шлюзы, такие как Stripe, и не храним вашу платеную информацию на наших серверах.',
    'faq.q3.question': 'Что такое режим "Инкогнито"?',
    'faq.q3.answer': 'В режиме "Инкогнито" ваш профиль виден только тем, кому вы поставили лайк. Это дает вам больше контроля над вашей конфиденциальностью.',
    'faq.q4.question': 'Как я могу пожаловаться на пользователя?',
    'faq.q4.answer': 'Вы можете пожаловаться на пользователя прямо из его профиля или из окна чата, нажав на меню с тремя точками и выбрав "Пожаловаться".',
    'faq.q5.question': 'Как работает "Автопоиск"?',
    'faq.q5.answer': '"Автопоиск" использует ваши предпочтения (возраст, интересы) чтобы найти для вас наиболее подходящих людей. Вы можете настроить фильтры, чтобы уточнить поиск.',
    'faq.q6.question': 'Почему тормозит приложение?',
    'faq.q6.answer': 'Это может быть связано с: \n1. Нестабильной связью с интернетом или большой нагрузкой на сеть (3G, 4G).\n2. Большим количеством открытых приложений или вкладок в браузере (рекомендуем закрыть лишние).\n3. Работой лишних приложений в автозапуске или фоновом режиме.',
    'faq.q7.question': 'Что означают звания в моем профиле?',
    'faq.q7.answer': 'Звания — это система достижений SwiftMatch. Одно лучшее звание присваивается автоматически: \n1. Король свиданий — для самых популярных пользователей (мэтч 90%+).\n2. Душа компании — если у вас много интересов (5+).\n3. Обаяшка — если вы заполнили поле "О себе".\n4. Романтик — базовый статус для всех остальных.',
    // Admin
    'admin.dashboard': 'Дашборд',
    'admin.users': 'Пользователи',
    'admin.reports': 'Жалобы',
    'admin.features': 'Функции',
    'admin.back_to_app': 'В приложение',
    'admin.logout': 'Выход',
    'admin.total_users': 'Всего пользователей',
    'admin.online_users': 'В сети',
    'admin.new_users': 'Новые сегодня',
    'admin.total_matches': 'Всего мэтчей',
    'admin.manage_users': 'Все пользователи',
    'admin.manage_features': 'Управление функциями',
    'admin.manage_reports': 'Управление жалобами',
    'admin.feature_desc': 'Включайте функции в реальном времени.',
    'admin.save': 'Сохранить',
    'admin.reset': 'Сбросить',
    'admin.status': 'Статус',
    'admin.joined': 'Регистрация',
    'admin.actions': 'Действия',
    'admin.city': 'Город',
    'admin.user_image': 'Фото',
    'admin.user_name': 'Имя',
    'admin.reporter': 'Пожаловался',
    'admin.reported_user': 'Пользователь',
    'admin.reason': 'Причина',
    'admin.date': 'Дата',
    'admin.report_new': 'Новая',
    'admin.report_resolved': 'Решена',
    'admin.view_profile': 'Просмотреть профиль',
    'admin.mark_resolved': 'Отметить как решенный',
    'admin.block_user': 'Заблокировать',
    'admin.delete_user': 'Удалить пользователя',
    'admin.no_reports': 'Жалоб пока нет',
    'admin.monetization.title': 'Монетизация',
    'admin.monetization.description': 'Настройте рекламные сети для вознаграждений.',
    'admin.monetization.google_desc': 'Показывать рекламу из Google AdMob.',
    'admin.monetization.yandex_desc': 'Показывать рекламу из Рекламной сети Яндекса.',
    'admin.monetization.ad_unit_id': 'ID рекламного блока',
    'admin.monetization.save_success_title': 'Настройки монетизации сохранены',
    'admin.monetization.save_success_desc': 'Изменения будут применены в приложении.',
    'admin.content.title': 'Контент',
    'admin.content.description': 'Управляйте списками, используемыми в приложении.',
    'admin.content.interests.title': 'Интересы',
    'admin.content.dating_goals.title': 'Цели знакомства',
    'admin.content.education.title': 'Образование',
    'admin.content.interests.save_toast': 'Список интересов обновлен',
    'admin.content.goals.save_toast': 'Список целей обновлен',
    'admin.content.education.save_toast': 'Список образования обновлен',
    'admin.messaging.title': 'Рассылка',
    'admin.messaging.description': 'Отправляйте сообщения всем пользователям приложения.',
    'admin.messaging.subject': 'Тема сообщения',
    'admin.messaging.message': 'Текст сообщения',
    'admin.messaging.send': 'Отправить рассылку',
    'admin.messaging.send_success_title': 'Рассылка отправлена',
    'admin.messaging.send_success_desc': 'Ваше сообщение скоро будет доставлено пользователям.',
    'dialog.delete_photo.title': 'Удалить фото?',
    'dialog.delete_photo.description': 'Это действие необратимо. Вы уверены, что хотите удалить эту фотографию?',
    'dialog.delete_photo.confirm': 'Удалить',
    'dialog.delete_photo.cancel': 'Отмена',
    'delete_photo_error.title': 'Нельзя удалить',
    'delete_photo_error.description': 'Вы не можете удалить последнее фото в галерее.',
    'settings.incognito.enabled_desc': 'Ваши визиты теперь скрыты.',
    'settings.incognito.disabled_desc': 'Ваши визиты снова видны.',
    'incognito.banner.title': 'Режим Инкогнито',
    'incognito.banner.description': 'Ваши посещения профилей других пользователей не будут отображаться в их активности.',
    'incognito.toast.title': 'Режим Инкогнито',
    'incognito.toast.description': 'Ваш визит на эту страницу останется анонимным.',
  },
  EN: {
    // Landing / SEO
    'landing.headline': 'Find your perfect match today',
    'landing.subheadline': 'SwiftMatch — a smart way to meet interesting people nearby.',
    'landing.stats.users.num': '1M+',
    'landing.stats.users.label': 'Users',
    'landing.stats.matches.num': '500K',
    'landing.stats.matches.label': 'Matches',
    'landing.stats.countries.num': '50+',
    'landing.stats.countries.label': 'Countries',

    // Bottom Nav
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.activity': 'Activity',
    'nav.chats': 'Chats',
    'nav.profile': 'Profile',
    // Common Buttons
    'button.continue': 'Continue',
    'button.skip': 'Skip',
    'button.save': 'Save',
    'button.back': 'Back',
    'button.like': 'Like',
    'button.message': 'Message',
    'button.send': 'Send',
    'button.search': 'Search',
    'button.filters': 'Filters',
    'button.autosearch': 'Auto-search',
    'button.load_more': 'Load more',
    'button.start': 'Start dating',
    'button.write_first': 'Write first',
    'button.close': 'Close',
    'button.unlock': 'Unlock for free',
    'button.watch': 'Watch',
    'button.not_now': 'Not now',
    'button.report': 'Report',
    'button.browse_profiles': 'Browse Profiles',
    // Profile
    'profile.edit': 'Edit',
    'profile.about': 'About Me',
    'profile.lifestyle': 'Data',
    'profile.interests': 'Interests',
    'profile.gallery': 'Gallery',
    'profile.add': 'Add',
    'profile.likes': 'Likes',
    'profile.matches': 'Matches',
    'profile.age': 'Age',
    'profile.city': 'Moscow',
    'profile.goal': 'Goal',
    'profile.goal_value': 'Serious relationship',
    'profile.height': 'Height',
    'profile.pro': 'PRO 💎',
    'profile.someone': 'Someone',
    // Lifestyle Labels
    'profile.label.zodiac': 'Zodiac',
    'profile.label.height': 'Height',
    'profile.label.goal': 'Goal',
    'profile.label.education': 'Education',
    'profile.label.job': 'Job',
    'profile.label.pets': 'Pets',
    'profile.label.sleep': 'Sleep',
    'profile.label.gender': 'Gender',
    'profile.label.looking_for': 'Looking for',
    // Activity
    'activity.title': 'Activity',
    'activity.likes': 'Likes',
    'activity.visits': 'Visits',
    'activity.all': 'All',
    'activity.new': 'new',
    'activity.empty': 'Nothing found',
    'activity.today_activity': 'Your activity today',
    'activity.msg_like': 'liked you',
    'activity.msg_visit': 'visited your profile',
    'activity.msg_match': 'new match with you!',
    'activity.unlock_title': 'Bonus',
    'activity.unlock_desc': 'Watch an ad to unlock the profile for free for 24 hours.',
    'activity.premium_title': 'Premium Access',
    'activity.premium_desc': 'Find out who liked you and get unlimited likes!',
    // Boost
    'boost.title': 'Boost Profile',
    'boost.desc': 'Your profile will be seen by 10x more people for one hour!',
    'boost.free': 'Free with Ad',
    'boost.paid': 'Buy Instant Boost',
    'boost.success_ad': 'Boost activated via ad! 🔥',
    'boost.success_paid': 'Boost purchased and activated! 🔥',
    'autosearch.title': 'Autosearch Access',
    'autosearch.desc': 'Get access to smart search by watching an ad or paying.',
    'autosearch.free': 'Free with Ad',
    'autosearch.paid': 'Buy Access',
    'autosearch.success_ad': 'Autosearch access unlocked!',
    'autosearch.success_paid': 'Autosearch access purchased!',
    // Chats
    'chats.title': 'Messages',
    'chats.subtitle': 'Your dialogs',
    'chats.search': 'Search chats...',
    'chats.online': 'Online',
    'chats.offline': 'Was recently',
    'chats.today': 'Today',
    'chats.typing': 'typing...',
    'chats.ai_themes': 'AI Reply Themes',
    'chats.close_themes': 'Close themes',
    'chats.placeholder': 'Your message...',
    // Home / Search
    'home.popular': 'Popular now',
    'home.headline': 'Your ideal match is waiting',
    'home.subheadline': 'Meet, chat and find love',
    'home.top_week': 'Top of the week',
    'home.recommend': 'Recommended',
    'home.nearby': 'Nearby',
    'home.searching': 'Searching for the best...',
    'home.results': 'Results',
    'home.no_results': 'No one found with these parameters.',
    'match.title': 'It\'s a Match!',
    'match.desc': 'You liked each other. Don\'t keep them waiting!',
    'match.insight': 'AI Insight',
    'swipes.nearby': 'profiles nearby',
    'match.insight_default': 'You are a great match!',
    // Filter
    'filter.who_to_see': 'Who are you looking for?',
    'filter.distance': 'Distance',
    'filter.goal': 'Dating Goal',
    'filter.goal.all': 'Any goal',
    'filter.gender.all': 'All',
    'filter.gender.male': 'Men',
    'filter.gender.female': 'Women',
    // Onboarding
    'onboarding.step1.title': "What's your name?",
    'onboarding.step1.desc': 'Name will be displayed in your profile.',
    'onboarding.step1.label': 'Name',
    'onboarding.step1.placeholder': 'Your name',
    'onboarding.step1.gender_label': 'Your gender',
    'onboarding.step1.male': 'Male',
    'onboarding.step1.female': 'Female',
    'onboarding.step2.title': 'A few details',
    'onboarding.step2.desc': 'This helps us find people nearby.',
    'onboarding.step2.age': 'Age',
    'onboarding.step2.height': 'Height (cm)',
    'onboarding.step2.city': 'City (optional)',
    'onboarding.step2.city_placeholder': 'Where are you located?',
    'onboarding.step3.title': 'Personal',
    'onboarding.step3.desc': 'Tell us about your goals and zodiac sign.',
    'onboarding.step3.goal_label': 'Dating goal',
    'onboarding.step3.goal_placeholder': 'Select goal',
    'onboarding.step3.zodiac_label': 'Zodiac sign',
    'onboarding.step3.zodiac_placeholder': 'Select sign',
    'onboarding.step4.title': 'Your interests',
    'onboarding.step4.desc': 'Select at least 1 so AI can draft a cool bio.',
    'onboarding.step5.title': 'Almost ready!',
    'onboarding.step5.desc': 'Add a bright photo and tell us about yourself or let AI help.',
    'onboarding.step5.photo_label': 'Select photo',
    'onboarding.step5.bio_label': 'About me',
    'onboarding.step5.bio_placeholder': 'Tell us about your hobbies...',
    'onboarding.toast.photo_added': 'Photo added!',
    'onboarding.toast.photo_desc': 'Your profile looks great now.',
    'onboarding.toast.bio_ai': 'Bio created by AI',
    'onboarding.toast.finish_title': 'Profile is ready!',
    'onboarding.toast.finish_desc': 'Welcome to SwiftMatch.',
    'onboarding.loc.detecting': 'Determining location...',
    'onboarding.loc.success': 'City determined: ',
    'onboarding.loc.fail': 'Could not determine city accurately',
    'onboarding.loc.denied': 'Geolocation access denied',
    // Report
    'report.title': 'Report User',
    'report.description': 'Your report is anonymous. Please select a reason, and we will review the situation.',
    'report.reason.spam': 'Spam',
    'report.reason.abuse': 'Abusive behavior',
    'report.reason.fake': 'Fake profile',
    'report.reason.scam': 'Scam',
    'report.reason.content': 'Inappropriate content',
    'report.details_placeholder': 'Additional details (optional)',
    'report.button.send': 'Send Report',
    'report.button.cancel': 'Cancel',
    'report.toast.success_title': 'Report sent',
    'report.toast.success_desc': 'Thank you! We will review your report on',
    'report.toast.no_reason_title': 'Select a reason',
    'report.toast.no_reason_desc': 'A reason is required to send a report.',
    // Settings
    'settings.account': 'Account',
    'settings.push_notifications': 'Push Notifications',
    'settings.email_newsletter': 'Email Newsletter',
    'settings.location': 'Geolocation',
    'settings.discovery': 'Show me',
    'settings.privacy': 'Privacy',
    'settings.incognito': 'Incognito',
    'settings.security': 'Security',
    'settings.security.status': 'OK',
    'settings.support': 'Support',
    'settings.support.chat_title': 'Contact Support',
    'settings.support.chat_desc': 'Chat with our team',
    'logout.title': 'You have been logged out',
    'logout.button': 'Logout',
    'delete_profile.button': 'Delete Profile',
    // Support Chat
    'support.title': 'Support',
    'support.placeholder': 'Write your message...',
    'support.greeting': 'Hello! How can we help you?',
    'support.response': 'Thank you for your message! Our specialist will contact you soon.',
    'support.faq_promo': 'Can\'t find an answer? Visit our',
    'support.faq_promo_link': 'FAQ section',
    // FAQ
    'faq.title': 'FAQ',
    'faq.page_title': 'Frequently Asked Questions',
    'faq.description': 'Answers to popular questions',
    'faq.q1.question': 'How can I change my profile picture?',
    'faq.q1.answer': 'You can change your photos by going to your profile, clicking the "Edit" button, and then tapping on your main photo or empty gallery slots.',
    'faq.q2.question': 'Is my payment information secure?',
    'faq.q2.answer': 'Yes, absolutely. We use industry-leading payment gateways like Stripe and do not store your payment information on our servers.',
    'faq.q3.question': 'What is "Incognito" mode?',
    'faq.q3.answer': 'In "Incognito" mode, your profile is only visible to people you have liked. This gives you more control over your privacy.',
    'faq.q4.question': 'How can I report a user?',
    'faq.q4.answer': 'You can report a user directly from their profile or from the chat window by clicking on the three-dots menu and selecting "Report".',
    'faq.q5.question': 'How does "Auto-search" work?',
    'faq.q5.answer': '"Auto-search" uses your preferences (age, interests) to find the most suitable people for you. You can adjust the filters to refine your search.',
    'faq.q6.question': 'Why is the app slow?',
    'faq.q6.answer': 'This could be due to: \n1. Unstable internet connection or high network load (3G, 4G).\n2. Many open apps or browser tabs (we recommend closing unused ones).\n3. Unnecessary background apps or startup items running on your device.',
    'faq.q7.question': 'What do the titles in my profile mean?',
    'faq.q7.answer': 'Titles are SwiftMatch\'s achievement system. One best title is assigned automatically: \n1. Dating King — for the most popular users (90%+ match).\n2. Life of the Party — if you have many interests (5+).\n3. Charming — if you filled out your bio.\n4. Romantic — the base status for everyone else.',
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.reports': 'Reports',
    'admin.features': 'Features',
    'admin.back_to_app': 'Back to App',
    'admin.logout': 'Logout',
    'admin.total_users': 'Total Users',
    'admin.online_users': 'Online Users',
    'admin.new_users': 'New Today',
    'admin.total_matches': 'Total Matches',
    'admin.manage_users': 'Manage Users',
    'admin.manage_features': 'Manage Features',
    'admin.manage_reports': 'Manage Reports',
    'admin.feature_desc': 'Enable or disable features in real-time.',
    'admin.save': 'Save Changes',
    'admin.reset': 'Reset',
    'admin.status': 'Status',
    'admin.joined': 'Joined',
    'admin.actions': 'Actions',
    'admin.city': 'City',
    'admin.user_image': 'Image',
    'admin.user_name': 'Name',
    'admin.reporter': 'Reporter',
    'admin.reported_user': 'User',
    'admin.reason': 'Reason',
    'admin.date': 'Date',
    'admin.report_new': 'New',
    'admin.report_resolved': 'Resolved',
    'admin.view_profile': 'View Profile',
    'admin.mark_resolved': 'Mark as Resolved',
    'admin.block_user': 'Block',
    'admin.delete_user': 'Delete User',
    'admin.no_reports': 'No reports yet',
    'admin.monetization.title': 'Monetization',
    'admin.monetization.description': 'Configure ad networks for rewards.',
    'admin.monetization.google_desc': 'Show ads from Google AdMob.',
    'admin.monetization.yandex_desc': 'Show ads from Yandex Advertising Network.',
    'admin.monetization.ad_unit_id': 'Ad Unit ID',
    'admin.monetization.save_success_title': 'Monetization settings saved',
    'admin.monetization.save_success_desc': 'Changes will be applied in the app.',
    'admin.content.title': 'Content',
    'admin.content.description': 'Manage lists used in the application, such as interests and dating goals.',
    'admin.content.interests.title': 'Interests',
    'admin.content.dating_goals.title': 'Dating Goals',
    'admin.content.education.title': 'Education',
    'admin.content.interests.save_toast': 'Interests list updated',
    'admin.content.goals.save_toast': 'Goals list updated',
    'admin.content.education.save_toast': 'Education list updated',
    'admin.messaging.title': 'Newsletter',
    'admin.messaging.description': 'Send messages to all application users.',
    'admin.messaging.subject': 'Message Subject',
    'admin.messaging.message': 'Message Body',
    'admin.messaging.send': 'Send Newsletter',
    'admin.messaging.send_success_title': 'Newsletter Sent',
    'admin.messaging.send_success_desc': 'Your message will be delivered to users shortly.',
    'dialog.delete_photo.title': 'Delete Photo?',
    'dialog.delete_photo.description': 'This action cannot be undone. Are you sure you want to delete this photo?',
    'dialog.delete_photo.confirm': 'Delete',
    'dialog.delete_photo.cancel': 'Cancel',
    'delete_photo_error.title': 'Cannot Delete',
    'delete_photo_error.description': 'You cannot delete the last photo in your gallery.',
    'settings.incognito.enabled_desc': 'Your visits are now hidden.',
    'settings.incognito.disabled_desc': 'Your visits are visible again.',
    'incognito.banner.title': 'Incognito Mode',
    'incognito.banner.description': 'Your visits to other profiles will not be shown in their activity.',
    'incognito.toast.title': 'Incognito Mode',
    'incognito.toast.description': 'Your visit to this page will remain anonymous.',
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('RU');
  const router = useRouter();
  const pathname = usePathname();

  const handleIdle = useCallback(() => {
    // Don't log out if on a public page like login/onboarding
    if (pathname === '/login' || pathname === '/onboarding') return;

    toast({
      title: language === 'RU' ? 'Сессия истекла' : 'Session Expired',
      description: language === 'RU' ? 'Вы были неактивны в течение 30 минут.' : 'You have been inactive for 30 minutes.',
    });
    router.push('/login');
  }, [router, language, pathname]);

  // 30 minutes in milliseconds
  const IDLE_TIMEOUT = 30 * 60 * 1000;
  useIdleTimer(handleIdle, IDLE_TIMEOUT);


  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  useEffect(() => {
    const savedLang = localStorage.getItem('app_lang') as Language;
    if (savedLang) setLanguageState(savedLang);
  }, []);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['RU']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
